name: Webhook

on:
  push:
    branches:
      - master

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/github-script@v7
         with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          script: |
            for (const branch of ['dev']) {
              github.rest.actions.createWorkflowDispatch({
                owner: 'amnezia-vpn',
                repo: 'amnezia.org-sources',
                workflow_id: 'build-and-deploy.yml',
                ref: branch,
              })
            }
